# Generated by Django 4.2 on 2025-08-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_item_product_quantity_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='product/category/'),
        ),
    ]
