# Generated by Django 4.2 on 2025-08-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_advertisement_mb_image_en_advertisement_mb_image_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_file/')),
            ],
            options={
                'verbose_name': 'Excel File',
                'verbose_name_plural': 'Excel File',
            },
        ),
    ]
