# Generated by Django 4.2 on 2025-08-23 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_excelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='excel_file/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])]),
        ),
    ]
